version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["5000"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"

[[transformers]]
name = "yapf"
enabled = true